config/routes.rb
Gtll::Application.routes.draw do

  root :to => 'pages#home'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :checkout_records

  resources :books do
    collection do
      get 'search'
    end
    member do
      put 'checkin'
      put 'checkout'
      put 'set_total_num_copies'
    end
  end

  match '/records', :to => 'books#records'
  match '/index', :to => 'books#index'
  match '/signup', :to => 'users#new'
  match '/emails', :to => 'users#all_user_emails'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/borrowers', :to => 'checkout_records#checked_out_users_list'

  match '/images/logo600', :to => 'public#logo600.png'
 
  match '/checkoutProcedure', :to => 'pages#checkoutProcedure'
  match '/notes', :to => 'pages#website_notes'
  match '/tech', :to => 'pages#tech_notes'

  match '/sampleCheckoutForm', :to => 'pages#sampleCheckoutForm.pdf'
  match '/searchInfo', :to => 'pages#searchInfo'
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base

  has_many :checkout_records, :dependent => :destroy
  has_many :books, :through => :checkout_records

  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :manager

  # A great deal of the following c/p or inspired from Hartl's ROR 3 Tutorial
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :email, :presence => true, :uniqueness => true
  validates :email, :format   => { :with => email_regex }
  validates :password, :presence => true, 
            :confirmation => true, 
            :length => { :within => 6..40 }

  before_save :encrypt_password

  default_scope :order => 'users.email ASC, users.name ASC'

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

  def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
      secure_hash("#{salt}--#{string}")
  end

  def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
      Digest::SHA2.hexdigest(string)
  end
end

app/controllers/users_controller.rb
#borrowed liberally from hartl's ROR 3 tutorial
class UsersController < ApplicationController
  before_filter :authenticate_user
  before_filter :authenticate_manager, :except => [:show]
  before_filter :valid_user, :only => [:show]

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def new
    @user = User.new
    @title = "Add New User"
  end

  def create
    @temp_user = current_user
    @user = User.new(params[:user])
    if @user.save
      redirect_to @temp_user
    else
      @title = "Add New User"
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @books = @user.books

    @books.each do | book |
      total = book.total_num_copies
      if total == 1
        book.destroy
      else
        book.total_num_copies = total - 1
        book.save
      end
    end

    @user.destroy
    flash[:success] = ["Successfully deleted", @user.name].join
    redirect_to users_path
  end

  def index
    @title = "All Users"
    @users = User.paginate(:per_page => 8, :page => params[:page])
  end

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def valid_user
    @user = User.find(params[:id])
    redirect_to(signin_path) unless current_user?(@user) || current_user.manager?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
  <div class="indexed_item">
    <%= link_to user.name, user_path(user.id) %></br>
    <%= user.email %>
    <%= link_to "Delete", user, :method => :delete, :confirm => 
    "ARE YOU SURE? This will delete ALL records for #{user.name}.
    If #{user.name} has checked out books, these copies 
    WILL BE ASSUMED LOST, and the book records will be changed accordingly.
    If this user has the only copy of a book, that book record will be DESTROYED.", 
    :title => "Delete #{user.name}",
    :class => "link-action" %> 
  </div>

app/views/users/all_user_emails.html.erb
<div class="infoBlock">
<h1>All Users</h1>
<% @users = User.all %>
<% @users.each do |user| %>
<%= ' ' + user.email + ';' %>
<% end %>


</div>

app/views/users/index.html.erb
<div id="pag_message">
  <h1>All users</h1></div>


<%= render 'shared/pag' %>

<% @users.each do |user| %>
<%= render user %>
<% end %>

<%= render 'shared/pag' %>

<% if @users.count > 5 %>
<a id ="link-to-top" href="#start">Top</a>
<% end %>

app/views/users/new.html.erb
<div class="infoBlock">
<h1>Add New User</h1>
  <%= render 'shared/user_error_messages' %>
  <%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.text_field :name, :placeholder => "Name" %>
  </div>
  <div class="field">
    <%= f.text_field :email, :placeholder => "Email" %>
  </div>
  <div class="field">
    <%= f.password_field :password, :placeholder => "password" %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, 
	:placeholder => "password confirmation" %>
  </div>
  <div class="checkbox">
    <%= f.check_box :manager %>
    <%= f.label :manager, "Manager" %>
  </div>
  <div class="actions">
  <%= f.submit "Add User", :class => "button" %>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="infoBlock">

  <!--User Name -->
  <h1>
    <%= @user.name %> 
  </h1>

  <!--Links for Manager -->
  <% if @user.manager? %>
  <%= link_to "Add New User", signup_path %><br/><br/>
  <%= link_to "Borrower Emails", borrowers_path %><br/><br/>
  <%= link_to "All User Emails", emails_path %><br/><br/>
  <%= link_to "Download CSV Records", records_path(:format => "csv"), 
  :confirm => "Download all book records as a CSV file?" %><br/><br/>
  <%= link_to "Download Excel Records", records_path(format: "xls"),
  :confirm => "Download all book records as an Excel file?"  %><br/><br/>
  <%= link_to "Notes for Manangers", notes_path %><br/><br/>
  <%= link_to "Notes for Tech Support", tech_path %>
  <% end %>
  <br>

  <!--Display User's Checked out Books, if any -->
  <% @books = @user.books %>
  <% if @books.count > 0 %>
  <h2>Books Checked Out</h2>
  <% @books = @user.books %>
  <% @books.each do |book| %>
  <div>
    <div class="title"> 
      <%= book.name %>
    </div>
    <!--Link to Check in Book -->
    <% if signed_in? and is_manager? %>
    <%= link_to "Check In", { :controller => "checkout_records", :action => :destroy,
    :book => book.id, :user => @user.id }, :method => :delete, :class => "link-action" %>
    <% end %>

    <% @book = book %>
    <%= render "shared/book_info" %>
  </div>
  <% end %>
  <% end %>


  <div id="account_info">Account Created on <%= @user.created_at.strftime('%B %d, %Y') %></div>

</div>