config/routes.rb
Gtll::Application.routes.draw do

  root :to => 'pages#home'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :checkout_records

  resources :books do
    collection do
      get 'search'
    end
    member do
      put 'checkin'
      put 'checkout'
      put 'set_total_num_copies'
    end
  end

  match '/records', :to => 'books#records'
  match '/index', :to => 'books#index'
  match '/signup', :to => 'users#new'
  match '/emails', :to => 'users#all_user_emails'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/borrowers', :to => 'checkout_records#checked_out_users_list'

  match '/images/logo600', :to => 'public#logo600.png'
 
  match '/checkoutProcedure', :to => 'pages#checkoutProcedure'
  match '/notes', :to => 'pages#website_notes'
  match '/tech', :to => 'pages#tech_notes'

  match '/sampleCheckoutForm', :to => 'pages#sampleCheckoutForm.pdf'
  match '/searchInfo', :to => 'pages#searchInfo'
end

app/views/pages/_footer.html.erb
<br/>
<div id="footer-txt">
-----------------------------------<br/>
Contact: textbooks@grinnell.edu<br/>
Search and dropdown menu icons designed by <a href="http://humphreybc.com/">Benjamin Humphrey</a>.<br/>
Success and failure icons designed by <a href="http://www.everaldo.com/">Everaldo Coelho</a>.<br/>
Icons retrieved from findicons.com<br/>
-----------------------------------
</div>

app/views/pages/checkoutProcedure.html.erb
<div class="infoBlock">
<h1>Borrowing Books</h1>
<h2>Materials to Bring</h2>
<ol>
  <li>Your Student ID</li>
  <li>A booklist <strong>printed from pweb</strong>. No other list will be accepted.</li> 
  <li>Lots of patience</li>
</ol>

<h2>Procedure</h2>

<p>Come to the library during our open hours with the materials specified
  above. Be prepared to wait in line. When you arrive, you will 
  receive a place card with your position in line; those at the back of the 
  line can leave and return later if necessary. However, if you fail to 
  return before your place card is called, the next person in line will be called.
</p>
<p>When your number is called, we will take your booklist and look up availible copies 
  of those books; be aware that we may not have all the books you require. You must read
  and sign a form (<%= link_to "Sample Checkout Form", 
		       sampleCheckoutForm_path(:format => 'pdf') %>) that defines the 
  conditions for borrowing a book.</p>

<h2>Printing Your Booklist</h2>
<ol>
  <li>Log in to Pioneer Web.</li>
  <li>Click on“Pictorial Class Lists & Book Lists”in the left menu.</li> 
  <li>Click on“View your book list based on your current courses and
    reserve texts” under the list of your courses.</li>
  <li>Print the resulting page(s).</li>
</ol>

<p><strong>Note:</strong> If you are taking a course that has not yet been added to your
  schedule on P-Web, print out a page containing the books for that course
  from the bookstore, and bring both that page and your syllabus in
  addition to your official booklist.</p>
</div>
<a id ="link-to-top" href="#start">Top</a>

app/views/pages/home.html.erb
<div class="infoBlock">
  <h2>About</h2>
  <p>The Grinnell Textbook Lending Library is a student-run organization 
    at Grinnell College that lends textbooks to students with financial need.
    The Library also loans caps and gowns to graduating seniors.</p> 
  <h2>Location</h2>
  <p>The Library is housed in Read Pit (next to the kitchen).</p>
  <h2>Hours</h2>
  <p>(Hours not yet posted for fall 2013 semester)</p>
  <h2>Borrowing Books</h2>
  <p>Visit our <%= link_to "For Borrowers", checkoutProcedure_path %> 
    page to read about the prodedure for checking out books. This information 
    will also be emailed out to all students, along with the Library's hours, 
    at the beginning of each semester.</p>
  <h2>Penalty for Missing Books</h2>
  <p>If you do not return a checked out book, you will lose your right
    to borrow books in the future. If for some reason you absolutely
    cannot return a book, you must email us and we will find a solution.</p>
  <h2>Book Records</h2>
  <p>To see the books you currently have checked out, sign in below with the 
    username and password you were given during checkout. If you've lost your 
    password, you can email [textbooks] to have your records emailed to you.</p>
  <h2>Contact</h2>
  <p>Email us at [textbooks] with any questions or comments.</p>
  
  <% if signed_in? == false %>
  <p><%= link_to "User Sign In", signin_path %></p>      
  <% end %>
</div>
<a id ="link-to-top" href="#start">Top</a>