config/routes.rb
Gtll::Application.routes.draw do

  root :to => 'pages#home'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :checkout_records

  resources :books do
    collection do
      get 'search'
    end
    member do
      put 'checkin'
      put 'checkout'
      put 'set_total_num_copies'
    end
  end

  match '/records', :to => 'books#records'
  match '/index', :to => 'books#index'
  match '/signup', :to => 'users#new'
  match '/emails', :to => 'users#all_user_emails'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/borrowers', :to => 'checkout_records#checked_out_users_list'

  match '/images/logo600', :to => 'public#logo600.png'
 
  match '/checkoutProcedure', :to => 'pages#checkoutProcedure'
  match '/notes', :to => 'pages#website_notes'
  match '/tech', :to => 'pages#tech_notes'

  match '/sampleCheckoutForm', :to => 'pages#sampleCheckoutForm.pdf'
  match '/searchInfo', :to => 'pages#searchInfo'
end

app/models/book.rb
require 'csv'

class Book < ActiveRecord::Base

  has_many :checkout_records
  has_many :users, :through => :checkout_records

  attr_accessible :name, :authors, :edition, :avail_copies, :total_num_copies

  validates :name, :authors, :presence => true
  validates_uniqueness_of :name, :scope => [:authors, :edition],
  :message => ": This book already is in the database; I won't permit a duplicate entry!"

  validates_numericality_of :avail_copies, :greater_than => -1
  validates_numericality_of :total_num_copies, :greater_than => 0

  validates_numericality_of :total_num_copies,
  :unless => Proc.new { |book| book.avail_copies.nil? },
  :greater_than_or_equal_to => :avail_copies

  default_scope :order => 'books.name ASC, books.authors ASC, books.edition ASC'


  #Based heavily on example in https://we.riseup.net/rails/simple-search-tutorial
  def self.search(title_search, authors_search)
    if title_search.nil? 
      title_search = ""
    end
    title = "%" + title_search + "%"
    if authors_search.nil?
      authors_search = ""
    end
    conditions = ['LOWER(name) LIKE ?', title.downcase]
    authors = authors_search.downcase.split(/\s*[,;]?\s/)
    authors.each{ |author|
      conditions[0].concat(' AND LOWER(authors) LIKE ?')
      conditions << "%" + author.downcase + "%"
    }
    find(:all, :conditions => conditions)
  end

  def checkin
    update_attributes(:avail_copies => [avail_copies, 1].sum)
  end

  def checkout
   update_attributes(:avail_copies => [avail_copies, -1].sum)
  end

  def set_total_num_copies(new_total_copies)
    new_avail = avail_copies

    if (new_total_copies > total_num_copies)
      new_avail = avail_copies + (new_total_copies - total_num_copies)
    end

    update_attributes(:total_num_copies => new_total_copies, 
                      :avail_copies => new_avail)
  end

# 'to_csv' method from code by Ryan Bates 
# retrieved from http://railscasts.com/episodes/362-exporting-csv-and-excel
# in May 2013
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |book|
        csv << book.attributes.values_at(*column_names)
      end
    end
  end
  
end

app/controllers/books_controller.rb
require 'csv'

class BooksController < ApplicationController
  before_filter :authenticate_user, :except => [:index, :search]
  before_filter :authenticate_manager, :except => [:index, :search]

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @title = "Add Book"
  end

  def index
    @title = "Index of Books"
    @books = Book.paginate(:per_page => 8, :page => params[:page])
  end

  def create
    @book = Book.new(params[:book])
    @book.total_num_copies = @book.avail_copies
    if @book.save
      flash[:success] = ["Book successfully added: Name = ", @book.name, ", 
           Authors = ", @book.authors, ", Edition = ", @book.edition, 
                        ", Copies = ", @book.avail_copies].join
      redirect_to new_book_path
    else 
      @title = "Add Book"
      render 'new'
    end
  end

# 'records' method based off of code by Ryan Bates 
# retrieved from http://railscasts.com/episodes/362-exporting-csv-and-excel
# in May, 2013
  def records
    respond_to do |format|
      format.csv { send_data Book.to_csv }
      format.xls { send_data Book.to_csv(col_sep: "\t") }
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if (@book.avail_copies == @book.total_num_copies)
      @book.destroy
      flash[:success] = ["Successfully deleted book: Name = ", @book.name, ", 
           Authors = ", @book.authors, ", Edition = ", @book.edition].join
    else
      flash[:failure] = "Cannot delete book; book has copies checked out."
    end
      redirect_to index_path
  end

#search based on https://we.riseup.net/rails/simple-search-tutorial
  def search
    @title = "Search"
    @books = Book.search(params[:title_search], 
                         params[:authors_search]).paginate(:per_page => 8, :page => params[:page])
    @temp_title = params[:title_search]
    @temp_authors = params[:authors_search]
  end

  def checkin
    @book = Book.find(params[:id])
    @book.checkin
    @book.save
    redirect_to index_path
  end

  def checkout
    @book = Book.find(params[:id])
    @book.checkout
    @book.save
    redirect_to index_path
  end

  def set_total_num_copies
    @book = Book.find(params[:id])
    @book.set_total_num_copies(params[:book][:total_num_copies].to_i)
    if @book.save
      flash[:success] = ["Total number of copies set to ", @book.total_num_copies].join
    else
      flash[:failure] = "Attempted to set total number of copies to less than number of available copies"
    end
    redirect_to book_path
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<!-- Book in index or search results -->
<div class="indexed_item">
<!-- If manager, show delete and checkout links -->
  <% if signed_in? and is_manager? %>
  <%= link_to "Delete", book, :method => :delete, :confirm => 
  "Are you SURE? 
  This will delete ALL records related to this book.", :title => "Delete #{book.name}", 
  :class => "link-action" %> 
  <% if book.avail_copies > 0 %>
  <%= link_to "Checkout", new_checkout_record_path(:param => book.id),
  :title => "Checkout #{book.name}",
  :class => "link-action" %>
  <% end %>
  <% end %>
  <!-- Book information -->
  <% @book = book %>
  <!-- Title -->
  <div class="title"> 
  <% if signed_in? and is_manager? %>
  <%= link_to "#{book.name}", book%>
  <% else %>
    <%= book.name %>
  <% end %>
  </div>
  <!-- Info -->
  <%= render "shared/book_info" %>
</div>

app/views/books/_search.html.erb
<!--based off Hartl & https://we.riseup.net/rails/simple-search-tutorial -->
<div id="search">
  <div id="sForm">
    <%= form_tag({:controller => "books", :action => "search"}, 
    :method => "get") do %>
    <%= text_field_tag :title_search, params[:title_search], 
	:placeholder => "Title" %>
    <%= text_field_tag :authors_search, params[:authors_search],
	:placeholder => "Author(s)" %>
  <div id="sButton">
    <%= submit_tag "Search", :name => nil %>
  </div>
  <% end %> 
  </div>
 <!-- <div id="sLink">
    <%= link_to "How do I search?", searchInfo_path %> -->
  </div>
</div>

app/views/books/index.html.erb
<div id="pag_message">
  On page <%= @books.current_page %> of <%= @books.total_pages %>
</div>

<%= render 'shared/pag'  %>

<% @books.each do |book| %>
<%= render book %>
<% end %>

<%= render 'shared/pag'  %>

<a id ="link-to-top" href="#start">Top</a>

app/views/books/new.html.erb
<div class="infoBlock">
<h1>Add Book</h1>
<%= render 'shared/book_error_messages' %>
<%= form_for(@book) do |f| %>
<div class="field">
  <%= f.text_field :name, :placeholder => "Title" %>
</div>
<div class="field">
  <%= f.text_field :authors, :placeholder => "Author(s)"  %>
</div>
<div class="field">
  <%= f.text_field :edition, :placeholder => "Edition"  %>
</div>
<div class="field">
  <%= f.text_field :avail_copies, :placeholder => "Available Copies"  %>
</div>
<div class="actions">
  <%= f.submit "Add book", :class => "button" %>
</div>
<% end %>
</div>

app/views/books/search.html.erb
<% if (@books.count == 0) %>
  <div id="pag_message">
    <p>Sorry, your search for:<br />
      Title: <%= @temp_title %><br> 
      Authors: <%= @temp_authors %><br>
      returned no results.</p>
    <p>Our search function is not as robust as commercial
      companies'.<br/>Check your spelling, and try searching by 
      only author or title, rather than both.</p>
  </div>
  <% else %>
  <div id="pag_message">
    <strong><%= @books.total_entries %> books found!</strong><br/>
    On page <%= @books.current_page %> of <%= @books.total_pages %>
    </div>
  
  <%= render 'shared/pag' %>
  <ul>
    <% @books.each do |book| %>
    <%= render book %>
    <% end %>
  </ul>
  
  <%= render 'shared/pag' %>
  
  <% if @books.count > 5 %>
  <a id ="link-to-top" href="#start">Top</a>
  <% end %>
  <% end %>

app/views/books/show.html.erb
<div class="infoBlock">
  <div class="title">
    <%= @book.name %>
  </div>
  <%= render "shared/book_info" %>
  <%= form_for @book, :url => {:action => "set_total_num_copies"} do |f| %>
  <%= render 'shared/book_error_messages' %>
  <div class="numCopiesField">
    <%= f.text_field :total_num_copies, :placeholder => "New Total Number of Copies"%>
      <br>
      <%= f.submit "Set Total Number of Copies", :class => "button" %>  
    </div>
    <% end %>
</div>