config/routes.rb
Gtll::Application.routes.draw do

  root :to => 'pages#home'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :checkout_records

  resources :books do
    collection do
      get 'search'
    end
    member do
      put 'checkin'
      put 'checkout'
      put 'set_total_num_copies'
    end
  end

  match '/records', :to => 'books#records'
  match '/index', :to => 'books#index'
  match '/signup', :to => 'users#new'
  match '/emails', :to => 'users#all_user_emails'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/borrowers', :to => 'checkout_records#checked_out_users_list'

  match '/images/logo600', :to => 'public#logo600.png'
 
  match '/checkoutProcedure', :to => 'pages#checkoutProcedure'
  match '/notes', :to => 'pages#website_notes'
  match '/tech', :to => 'pages#tech_notes'

  match '/sampleCheckoutForm', :to => 'pages#sampleCheckoutForm.pdf'
  match '/searchInfo', :to => 'pages#searchInfo'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grinnell Textbook Lending Library | <%= @title %></title>
<meta name="viewport" content="width=device-width, minimumscale=
1.0, maximum-scale=1.0" />
    <%= csrf_meta_tag %>
    <%= javascript_include_tag :defaults %>
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  </head>
  <body>
    <wrapper>     <!--Wrapper for all content except footer -->
      <top>     <!--Wrapper for logo, navigation, and search -->
	<header>
	  <!-- 'to top of page' link -->
	  <a name="start"></a>
	  <!--Normal logo -->
	  <a id="title" href="/"><img alt="Grinnell Textbook Lending Library"
			   class="round"
			   src="/images/trad_banner.png" /> </a>
	  <!--Content for small screens only -->
	  <div id="mobile">
	  <!--Mobile logo -->
	    <a href="/"><img alt="Grinnell Textbook Lending Library"
			   class="round"
			   src="/images/mobile_banner.png" /> </a>
	  <!--Mobile buttons to show/hide search and nav -->
	    <div id="icons">
	    <a href="#" onclick=toggle("search")>
	      <img src= "/images/64_search.png" alt= "Search for books" /></a>
	    <a href="#" onclick=toggle("nav")>
	      <img src= "/images/64_dropdown.png" alt= "Open Navigation" /></a>
	    </div>
	  </div>
	  <!--Navigation links -->
	  <div id="nav">
	    <ul class="links">
              <li><%= link_to "Home", root_path%></li>
              <li><%= link_to "Index", index_path%></li>
              <% if signed_in? %>
              <% if is_manager? %>
              <li><%= link_to "New Book", new_book_path%></li>
              <li><%= link_to "All Users", users_path %></li>
              <% end %>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
              <% end %>
	    </ul>
	  </div>
	</header>
	<!-- Search box -->
	<%= render 'books/search' %>
      </top>
      <content>
	<!-- Flash messages -->
	<% flash.each do |key, value| %>
	  <div id="flash_<%= key %>"><%= value %></div>
	<% end %>
	<!-- Rest of the content -->
	<%= yield %>
      </content>
    </wrapper>
    <!-- Footer -->
    <footer>
      <%= render 'pages/footer' %>
    </footer>
  </body>
</html>